### ISSUE TITLE
Test Bug

### ISSUE THREAD

**Issue by Nino9614** [Futureglobe/SnipAway#1]
**Describe the bug**
This is a test bug

**Steps to reproduce the bug**
Its not possible to explain the bug

**Expected behavior**
I expected that this issue gets created

**Screenshots**
No screenshots

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10
 - Version: 1.1.6

**Comment by Futureglobe** [comment]
Bug reporting working
